---

- name: Setup Oracle to start on boot (RHEL 6)
  block:
    - name: Get dbora file
      get_url: 
        url: "https://gist.githubusercontent.com/chiita/906bafd11e88bea3bdfc/raw/561f8e2413b8737fe1ae3100d6287d1f215ecfd1/dbora"
        dest: /etc/init.d/dbora
        mode: 0755

    - name: Update the dbora file with the correct Oracle Home
      lineinfile:
        path: /etc/init.d/dbora
        regexp: '^export ORACLE_HOME='
        line: 'export ORACLE_HOME={{ oracle_home }}'

    - name: Enable the dbora service
      service:
        name: dbora
        enabled: yes

    - name: Start the dbora service
      service:
        name: dbora
        state: started
      become: yes
  when: ansible_distribution_major_version == "6"
- name: Setup Oracle to start on boot (RHEL 7)
  block:
    - name: Create Oracle Unit File
      template: src=oracle-rdbms.service.j2 dest=/etc/systemd/system/oracle-rdbms.service
    - name: Enable the Oracle service to start on boot
      systemd:
        daemon_reload: yes
        enabled: yes
        name: oracle-rdbms.service
  tags:
    - oracle_service
  when: ansible_distribution_major_version == "7"